export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_ORGANIZATIONS = 'SET_CURRENT_ORGANIZATIONS';
export const SET_CURRENT_SELLERS = 'SET_CURRENT_SELLERS';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
